"use strict";

/* eslint-disable global-require */
const impls = {
  Attr: require("./attributes/Attr-impl"),
  NamedNodeMap: require("./attributes/NamedNodeMap-impl"),

  DOMParser: require("./domparsing/DOMParser-impl"),

  CompositionEvent: require("./events/CompositionEvent-impl"),
  CustomEvent: require("./events/CustomEvent-impl"),
  ErrorEvent: require("./events/ErrorEvent-impl"),
  Event: require("./events/Event-impl"),
  EventTarget: require("./events/EventTarget-impl"),
  FocusEvent: require("./events/FocusEvent-impl"),
  HashChangeEvent: require("./events/HashChangeEvent-impl"),
  KeyboardEvent: require("./events/KeyboardEvent-impl"),
  MessageEvent: require("./events/MessageEvent-impl"),
  MouseEvent: require("./events/MouseEvent-impl"),
  PopStateEvent: require("./events/PopStateEvent-impl"),
  ProgressEvent: require("./events/ProgressEvent-impl"),
  TouchEvent: require("./events/TouchEvent-impl"),
  UIEvent: require("./events/UIEvent-impl"),
  WheelEvent: require("./events/WheelEvent-impl"),

  Blob: require("./file-api/Blob-impl"),
  File: require("./file-api/File-impl"),
  FileList: require("./file-api/FileList-impl"),
  FileReader: require("./file-api/FileReader-impl"),

  Navigator: require("./navigator/Navigator-impl"),
  NavigatorConcurrentHardware: require("./navigator/NavigatorConcurrentHardware-impl"),
  NavigatorCookies: require("./navigator/NavigatorCookies-impl"),
  NavigatorID: require("./navigator/NavigatorID-impl"),
  NavigatorLanguage: require("./navigator/NavigatorLanguage-impl"),
  NavigatorOnLine: require("./navigator/NavigatorOnLine-impl"),
  NavigatorPlugins: require("./navigator/NavigatorPlugins-impl"),

  CDATASection: require("./nodes/CDATASection-impl"),
  CharacterData: require("./nodes/CharacterData-impl"),
  ChildNode: require("./nodes/ChildNode-impl"),
  Comment: require("./nodes/Comment-impl"),
  DOMImplementation: require("./nodes/DOMImplementation-impl"),
  DOMStringMap: require("./nodes/DOMStringMap-impl"),
  DOMTokenList: require("./nodes/DOMTokenList-impl"),
  Document: require("./nodes/Document-impl"),
  DocumentFragment: require("./nodes/DocumentFragment-impl"),
  DocumentType: require("./nodes/DocumentType-impl"),
  Element: require("./nodes/Element-impl"),
  ElementCSSInlineStyle: require("./nodes/ElementCSSInlineStyle-impl"),
  ElementContentEditable: require("./nodes/ElementContentEditable-impl"),
  GlobalEventHandlers: require("./nodes/GlobalEventHandlers-impl"),
  HTMLAnchorElement: require("./nodes/HTMLAnchorElement-impl"),
  HTMLAppletElement: require("./nodes/HTMLAppletElement-impl"),
  HTMLAreaElement: require("./nodes/HTMLAreaElement-impl"),
  HTMLAudioElement: require("./nodes/HTMLAudioElement-impl"),
  HTMLBRElement: require("./nodes/HTMLBRElement-impl"),
  HTMLBaseElement: require("./nodes/HTMLBaseElement-impl"),
  HTMLBodyElement: require("./nodes/HTMLBodyElement-impl"),
  HTMLButtonElement: require("./nodes/HTMLButtonElement-impl"),
  HTMLCanvasElement: require("./nodes/HTMLCanvasElement-impl"),
  HTMLCollection: require("./nodes/HTMLCollection-impl"),
  HTMLDListElement: require("./nodes/HTMLDListElement-impl"),
  HTMLDataElement: require("./nodes/HTMLDataElement-impl"),
  HTMLDataListElement: require("./nodes/HTMLDataListElement-impl"),
  HTMLDetailsElement: require("./nodes/HTMLDetailsElement-impl"),
  HTMLDialogElement: require("./nodes/HTMLDialogElement-impl"),
  HTMLDirectoryElement: require("./nodes/HTMLDirectoryElement-impl"),
  HTMLDivElement: require("./nodes/HTMLDivElement-impl"),
  HTMLElement: require("./nodes/HTMLElement-impl"),
  HTMLEmbedElement: require("./nodes/HTMLEmbedElement-impl"),
  HTMLFieldSetElement: require("./nodes/HTMLFieldSetElement-impl"),
  HTMLFontElement: require("./nodes/HTMLFontElement-impl"),
  HTMLFormElement: require("./nodes/HTMLFormElement-impl"),
  HTMLFrameElement: require("./nodes/HTMLFrameElement-impl"),
  HTMLFrameSetElement: require("./nodes/HTMLFrameSetElement-impl"),
  HTMLHRElement: require("./nodes/HTMLHRElement-impl"),
  HTMLHeadElement: require("./nodes/HTMLHeadElement-impl"),
  HTMLHeadingElement: require("./nodes/HTMLHeadingElement-impl"),
  HTMLHtmlElement: require("./nodes/HTMLHtmlElement-impl"),
  HTMLHyperlinkElementUtils: require("./nodes/HTMLHyperlinkElementUtils-impl"),
  HTMLIFrameElement: require("./nodes/HTMLIFrameElement-impl"),
  HTMLImageElement: require("./nodes/HTMLImageElement-impl"),
  HTMLInputElement: require("./nodes/HTMLInputElement-impl"),
  HTMLLIElement: require("./nodes/HTMLLIElement-impl"),
  HTMLLabelElement: require("./nodes/HTMLLabelElement-impl"),
  HTMLLegendElement: require("./nodes/HTMLLegendElement-impl"),
  HTMLLinkElement: require("./nodes/HTMLLinkElement-impl"),
  HTMLMapElement: require("./nodes/HTMLMapElement-impl"),
  HTMLMarqueeElement: require("./nodes/HTMLMarqueeElement-impl"),
  HTMLMediaElement: require("./nodes/HTMLMediaElement-impl"),
  HTMLMenuElement: require("./nodes/HTMLMenuElement-impl"),
  HTMLMetaElement: require("./nodes/HTMLMetaElement-impl"),
  HTMLMeterElement: require("./nodes/HTMLMeterElement-impl"),
  HTMLModElement: require("./nodes/HTMLModElement-impl"),
  HTMLOListElement: require("./nodes/HTMLOListElement-impl"),
  HTMLObjectElement: require("./nodes/HTMLObjectElement-impl"),
  HTMLOptGroupElement: require("./nodes/HTMLOptGroupElement-impl"),
  HTMLOptionElement: require("./nodes/HTMLOptionElement-impl"),
  HTMLOptionsCollection: require("./nodes/HTMLOptionsCollection-impl"),
  HTMLOutputElement: require("./nodes/HTMLOutputElement-impl"),
  HTMLParagraphElement: require("./nodes/HTMLParagraphElement-impl"),
  HTMLParamElement: require("./nodes/HTMLParamElement-impl"),
  HTMLPictureElement: require("./nodes/HTMLPictureElement-impl"),
  HTMLPreElement: require("./nodes/HTMLPreElement-impl"),
  HTMLProgressElement: require("./nodes/HTMLProgressElement-impl"),
  HTMLQuoteElement: require("./nodes/HTMLQuoteElement-impl"),
  HTMLScriptElement: require("./nodes/HTMLScriptElement-impl"),
  HTMLSelectElement: require("./nodes/HTMLSelectElement-impl"),
  HTMLSourceElement: require("./nodes/HTMLSourceElement-impl"),
  HTMLSpanElement: require("./nodes/HTMLSpanElement-impl"),
  HTMLStyleElement: require("./nodes/HTMLStyleElement-impl"),
  HTMLTableCaptionElement: require("./nodes/HTMLTableCaptionElement-impl"),
  HTMLTableCellElement: require("./nodes/HTMLTableCellElement-impl"),
  HTMLTableColElement: require("./nodes/HTMLTableColElement-impl"),
  HTMLTableElement: require("./nodes/HTMLTableElement-impl"),
  HTMLTableRowElement: require("./nodes/HTMLTableRowElement-impl"),
  HTMLTableSectionElement: require("./nodes/HTMLTableSectionElement-impl"),
  HTMLTemplateElement: require("./nodes/HTMLTemplateElement-impl"),
  HTMLTextAreaElement: require("./nodes/HTMLTextAreaElement-impl"),
  HTMLTimeElement: require("./nodes/HTMLTimeElement-impl"),
  HTMLTitleElement: require("./nodes/HTMLTitleElement-impl"),
  HTMLTrackElement: require("./nodes/HTMLTrackElement-impl"),
  HTMLUListElement: require("./nodes/HTMLUListElement-impl"),
  HTMLUnknownElement: require("./nodes/HTMLUnknownElement-impl"),
  HTMLVideoElement: require("./nodes/HTMLVideoElement-impl"),
  LinkStyle: require("./nodes/LinkStyle-impl"),
  Node: require("./nodes/Node-impl"),
  NodeList: require("./nodes/NodeList-impl"),
  NonDocumentTypeChildNode: require("./nodes/NonDocumentTypeChildNode-impl"),
  NonElementParentNode: require("./nodes/NonElementParentNode-impl"),
  ParentNode: require("./nodes/ParentNode-impl"),
  ProcessingInstruction: require("./nodes/ProcessingInstruction-impl"),
  SVGElement: require("./nodes/SVGElement-impl"),
  SVGGraphicsElement: require("./nodes/SVGGraphicsElement-impl"),
  SVGSVGElement: require("./nodes/SVGSVGElement-impl"),
  SVGTests: require("./nodes/SVGTests-impl"),
  Text: require("./nodes/Text-impl"),
  WindowEventHandlers: require("./nodes/WindowEventHandlers-impl"),
  XMLDocument: require("./nodes/XMLDocument-impl"),

  SVGAnimatedString: require("./svg/SVGAnimatedString-impl"),
  SVGNumber: require("./svg/SVGNumber-impl"),
  SVGStringList: require("./svg/SVGStringList-impl"),

  NodeIterator: require("./traversal/NodeIterator-impl"),
  TreeWalker: require("./traversal/TreeWalker-impl"),

  External: require("./window/External-impl"),
  History: require("./window/History-impl"),
  Location: require("./window/Location-impl"),

  FormData: require("./xhr/FormData-impl"),
  XMLHttpRequestEventTarget: require("./xhr/XMLHttpRequestEventTarget-impl"),
  XMLHttpRequestUpload: require("./xhr/XMLHttpRequestUpload-impl")
};

const extras = {
  DOMException: require("domexception"),
  URL: require("whatwg-url").URL,
  URLSearchParams: require("whatwg-url").URLSearchParams,

  // Needs migration to webidl2js eventually.
  NamedNodeMap: require("./attributes").NamedNodeMap
};
/* eslint-enable global-require */

// These need to be cleaned up...
require("../level2/style")(extras);
require("../level3/xpath")(extras);

// These are OK but need migration to webidl2js eventually.
require("./node-filter")(extras);

module.exports = {
  impls,
  extras
};
